### PR TITLE
qt6 compilation

### PR DESCRIPTION
**Pull request by tristancabel**
compilation ok with qt6.  
I will add the environment used

### CODE REVIEW

**Comment by tristancabel** [comment]
Bonjour @fredboudon . la recette marche chez moi avec qt5 pour: 
conda build . -c msys2 -c conda-forge -c fredboudon --python 38 --numpy 116 --no-test

conda build . -c msys2 -c conda-forge -c fredboudon --python 39 --numpy 119 --no-test

sans l'option --no-test, cela fait une erreur "Incompatible component merge:"

**Comment by fredboudon** [comment]
Strange. Which conda module cannot be merged ? Maybe we need to change the test section (or run section) of the meta.yaml.

**Comment by tristancabel** [comment]
Exactly like the build error from ubuntu-latest 39, 119: 

```
 raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
ValueError: Incompatible component merge:
  - 'mpi_mpich_*'
  - 'mpi_mpich_tempest*'
```

**Comment by tristancabel** [comment]
salut, tu peux essayer de lancer les builds?

**Comment by tristancabel** [comment]
from https://github.com/fredboudon/plantgl/actions/runs/3127635192/jobs/5123561331 
build OK package created
login NOK: ANACONDA_LOGIN is not defined

I let you take care of the rest

**Pull request merged**
